title: A Marketplace for Edge Federated ML
description: Research project on federated learning marketplaces
theme: jekyll-theme-cayman
author: Tien-Dung Cao
email: dung.cao@ttu.edu.vn
show_downloads: true
